# Workflow derived from https://github.com/r-lib/actions/blob/v2/examples/check-standard.yaml
name: check-package

on:
  push:
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::roxygen2
          needs: check

      - name: Generate Rd docs with roxygen2
        run: Rscript -e 'roxygen2::roxygenise()'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: false
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
